<?php

/**
 * @file
 * Contains boletim.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function boletim_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the boletim module.
    case 'help.page.boletim':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Boletim') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function boletim_theme() {
  return [

    'boletim' => [
      'template' => 'boletim',
#      'render element' => 'form',
      'variables' => [
        'form' => NULL
      ],
      
    ],

  ];
}

function boletim_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'boletim_key':
     $message['from'] = 'noreply.sites.fflch@usp.br';
     #$message['from'] = \Drupal::config('system.site')->get('mail');
     $message['subject'] = $params['subject'];
     $message['body'][] = $params['message'];
     $message['headers'] = array(
       'content-type' => 'text/html',
       'charset' => 'UTF-8',
       'format' => 'flowed',
       'delsp' => 'yes',
       'from' => \Drupal::config('system.site')->get('mail')
    );
   break;
 }
}


