<?php

/**
 * @file
 * Contains boletim.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Utility\Mail;

/**
 * Implements hook_help().
 */
function boletim_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the boletim module.
    case 'help.page.boletim':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Boletim') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function boletim_theme() {
  return [

    'boletim' => [
      'template' => 'boletim',
#      'render element' => 'form',
      'variables' => [
        'form' => NULL
      ],
      
    ],

  ];
}

function boletim_mail($key, &$message, $params) {
 $options = array(
   'langcode' => $message['langcode'],
 );
 switch ($key) {
   case 'boletim_key':
     $from = Mail::formatDisplayName($params['from_name']) . ' <' . $params['from_mail'] . '>';
     $message['from'] = $from;
     $message['reply-to'] = $from;
     $message['subject'] = $params['subject'];
     $message['body'][] = $params['message'];
     $message['headers'] = array(
       'content-type' => 'text/html',
       'charset' => 'UTF-8',
       'format' => 'flowed',
       'delsp' => 'yes',
       'From' => $from,
       'Sender' => $from,
       'Return-Path' => $from,
       'Reply-to' => $from,
    );
   break;
 }

}


